// TODO : 
"addi s1, zero, 16 \n\t"    
"addi %[arith_cnt], %[arith_cnt], 1 \n\t"  

"L1: \n\t"
"lh t0, 0(%[h]) \n\t" 
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"      
"lh t1, 0(%[x]) \n\t"
"addi %[lw_cnt], %[lw_cnt], 1 \n\t"        
"add t2, t0, t1 \n\t"   
"addi %[arith_cnt], %[arith_cnt], 1 \n\t"    
"sh t2, 0(%[y]) \n\t"    
"addi %[sw_cnt], %[sw_cnt], 1 \n\t"   
"addi %[h], %[h], 2 \n\t"   
"addi %[arith_cnt], %[arith_cnt], 1 \n\t"  
"addi %[x], %[x], 2 \n\t"   
"addi %[arith_cnt], %[arith_cnt], 1 \n\t"  
"addi %[y], %[y], 2 \n\t"   
"addi %[arith_cnt], %[arith_cnt], 1 \n\t"  
"addi s1, s1, -1 \n\t"      
"addi %[arith_cnt], %[arith_cnt], 1 \n\t"  

"addi %[others_cnt], %[others_cnt], 1 \n\t" 
"bne s1, zero, L1 \n\t"  
